### ISSUE TITLE
Gyroflow Toolbox doesn't handle symlinks correctly

### ISSUE THREAD

**Issue by latenitefilms** [latenitefilms/GyroflowToolbox#20]
> I had the same problem today, where fcp would not apply the stabilization data from the GyroFlow processed data file.
> 
> In my case, after 6 hours of trying everything under the sun, I figured out the cause. I use an external ssd for my fcp media. if the external ssd is mounted in a directory (like movie) as a Symbolic Link, GyroFlow Toolbox will not locate the GyroFlow data file, therefore no stabilization in fcp.
> 
> When I finally deleted the Symbolic Link to the external ssd, and started using the ssd as a drive (shows up in the Finder on the left hand column, everything started working normal.
> 
> My guess is that your issue may also be due to a broken link to the GyroFlow processed data file.
> 
> Hope this helps.
> 
> _Originally posted by @scrappyTURTLEcom in https://github.com/latenitefilms/GyroflowToolbox/issues/19#issuecomment-1583909111_

**Comment by lss584** [comment]
Hi,

I'm facing the same problem and have tried various troubleshooting steps without success.

I noticed that you mentioned using an external SSD for FCP media and the issue arising when the SSD is mounted in a directory as a Symbolic Link. You resolved the problem by deleting the Symbolic Link and using the SSD as a drive instead.

I followed your steps, but unfortunately, I'm still experiencing the same issue. I suspect it may be due to a broken link to the GyroFlow processed data file.

Could you please provide further guidance or any additional troubleshooting steps that could help resolve this issue? Your expertise and insights would be greatly appreciated.

Thank you in advance for your assistance.

**Comment by latenitefilms** [comment]
Note to self... @Iss584 has also posted this question on Discord, so will reply there.

**Comment by scrappyTURTLEcom** [comment]
I am pretty sure the problem is the broken link to the GyroFlow processed data file(you must use the “processed" file). I remember looking at bunch of log files on Mac, seeing errors, that looked like, associated with not finding the data.

Using Finder on Mac, your SSD should show up in the side bar.  See the pic below, PRO-G40-2TB is my SSD. 
￼

Notice my test project: vibration3 Library, Project, Media, and Gyroflow “processed" data file are all in the same directory on the SSD. 
I don’t run the FCP Library in the default Movies directory with data files on SSD. I have a feeling this could cause broken link as well (not sure). 
See the pic below, showing the details for Library vibration3 on FCP. 

￼

Hope this helps.

Soheil

**Comment by latenitefilms** [comment]
Thanks for your reply Soheil (although we can't see your images)!

I'll do some proper digging into this during the week.

It's a bit odd though, because we actually just import the Gyroflow project data into the Final Cut Pro library when you open it, and Final Cut Pro just passes the pixels to Gyroflow - so, in theory at least, Gyroflow Toolbox doesn't actually need to access any files on the file system. It doesn't actually "open" the media for rendering - that pixel data comes from Final Cut Pro.

**Comment by scrappyTURTLEcom** [comment]
I have included the 2 images in jpg below. In this case, perhaps it is FCP that looses the link!! I’m guessing here.
￼￼

**Comment by latenitefilms** [comment]
I believe this has been addressed in v1.1.0, but if you're still having issues, let me know!
